package eu.kalafatic.evolution.model.orchestration;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
public interface Orchestrator extends EObject {
    String getId();
    void setId(String value);
    String getName();
    void setName(String value);
    EList<Agent> getAgents();
    EList<Task> getTasks();
    Git getGit();
    void setGit(Git value);
    Maven getMaven();
    void setMaven(Maven value);
    LLM getLlm();
    void setLlm(LLM value);
    Compiler getCompiler();
    void setCompiler(Compiler value);
    Ollama getOllama();
    void setOllama(Ollama value);
    AiChat getAiChat();
    void setAiChat(AiChat value);
    NeuronAI getNeuronAI();
    void setNeuronAI(NeuronAI value);
    String getRemoteModel();
    void setRemoteModel(String value);
    AiMode getAiMode();
    void setAiMode(AiMode value);
    String getMcpServerUrl();
    void setMcpServerUrl(String value);
    String getOpenAiToken();
    void setOpenAiToken(String value);
    String getOpenAiModel();
    void setOpenAiModel(String value);
    String getLocalModel();
    void setLocalModel(String value);
    String getHybridModel();
    void setHybridModel(String value);
    boolean isOfflineMode();
    void setOfflineMode(boolean value);
    SelfDevSession getSelfDevSession();
    void setSelfDevSession(SelfDevSession value);
    Database getDatabase();
    void setDatabase(Database value);
    FileConfig getFileConfig();
    void setFileConfig(FileConfig value);
    String getSharedMemory();
    void setSharedMemory(String value);
    EList<Lineage> getLineages();
    EList<Pressure> getPressures();
}
