package eu.kalafatic.evolution.model.orchestration;
import org.eclipse.emf.ecore.EFactory;
public interface OrchestrationFactory extends EFactory {
    OrchestrationFactory eINSTANCE = eu.kalafatic.evolution.model.orchestration.impl.OrchestrationFactoryImpl.init();
    Task createTask();
    Agent createAgent();
    Orchestrator createOrchestrator();
    Git createGit();
    Maven createMaven();
    LLM createLLM();
    Compiler createCompiler();
    Command createCommand();
    Ollama createOllama();
    AiChat createAiChat();
    NeuronAI createNeuronAI();
    EvoProject createEvoProject();
    AccessRule createAccessRule();
    NetworkRule createNetworkRule();
    MemoryRule createMemoryRule();
    SecretRule createSecretRule();
    SelfDevSession createSelfDevSession();
    Iteration createIteration();
    EvaluationResult createEvaluationResult();
    Database createDatabase();
    FileConfig createFileConfig();
    Artifact createArtifact();
    Lineage createLineage();
    EvolutionStep createEvolutionStep();
    Mutation createMutation();
    Evaluation createEvaluation();
    Pressure createPressure();
    Property createProperty();
    OrchestrationPackage getOrchestrationPackage();
}
