/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.AIProvider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AIProviderValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateUrl(String value);
	boolean validateApiKey(String value);
	boolean validateFormat(String value);
	boolean validateLocal(boolean value);
	boolean validateDefaultModel(String value);
	boolean validateApiKeyEncrypted(boolean value);
	boolean validateUseEnvVar(boolean value);
	boolean validateEnvVarName(String value);
	boolean validateState(String value);
	boolean validateStateDescription(String value);
	boolean validateRating(int value);
	boolean validateRatingAnalyze(int value);
	boolean validateRatingChat(int value);
	boolean validateRatingProgramming(int value);
}
