/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.ChatMessage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChatMessageValidator {
	boolean validate();

	boolean validateIndex(int value);
	boolean validateSender(String value);
	boolean validateText(String value);
	boolean validateColor(String value);
	boolean validateIsBold(boolean value);
	boolean validateIsItalic(boolean value);
	boolean validateAgentType(String value);
	boolean validateTimestamp(String value);

	boolean validatePriority(int value);

	boolean validateSequenceNumber(long value);

	boolean validateTurnId(String value);

	boolean validateIsTerminal(boolean value);
}
