/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Compiler}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompilerValidator {
	boolean validate();

	boolean validateSourceVersion(String value);
	boolean validateTargetVersion(String value);
	boolean validateCPath(String value);
	boolean validateCppPath(String value);
	boolean validateMakePath(String value);
	boolean validateCmakePath(String value);
	boolean validateTestStatus(String value);
}
