/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.SelfDevDecision;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.EvaluationResult}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EvaluationResultValidator {
	boolean validate();

	boolean validateSuccess(boolean value);
	boolean validateTestPassRate(double value);
	boolean validateCoverageChange(double value);
	boolean validateErrors(EList<String> value);
	boolean validateDecision(SelfDevDecision value);
	boolean validateUserSatisfaction(int value);

	boolean validateFitnessHistory(String value);
}
