/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Git}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GitValidator {
	boolean validate();

	boolean validateRepositoryUrl(String value);
	boolean validateBranch(String value);
	boolean validateUsername(String value);
	boolean validateLocalPath(String value);
	boolean validateTestStatus(String value);

	boolean validateBranchName(String value);

	boolean validateCommitMsg(String value);

	boolean validatePassword(String value);
}
