/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.EvaluationResult;
import eu.kalafatic.evolution.model.orchestration.IterationStatus;
import eu.kalafatic.evolution.model.orchestration.Task;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Iteration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IterationValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateBranchName(String value);
	boolean validateTasks(EList<Task> value);
	boolean validateEvaluationResult(EvaluationResult value);
	boolean validateStatus(IterationStatus value);
	boolean validatePhase(String value);
	boolean validateComments(String value);
	boolean validateRating(int value);
	boolean validateRationale(String value);

	boolean validateJustification(String value);

	boolean validateSemanticPressure(String value);

	boolean validateSurvivalArgument(String value);

	boolean validateTradeoffs(String value);

	boolean validateFailureRisks(String value);
}
