/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Maven}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MavenValidator {
	boolean validate();

	boolean validateGoals(EList<String> value);
	boolean validateProfiles(EList<String> value);
	boolean validateTestStatus(String value);
}
