/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.Iteration;
import eu.kalafatic.evolution.model.orchestration.SelfDevStatus;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.SelfDevSession}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SelfDevSessionValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateStartTime(long value);
	boolean validateMaxIterations(int value);
	boolean validateStatus(SelfDevStatus value);
	boolean validateIterations(EList<Iteration> value);
	boolean validateRationale(String value);
	boolean validateInitialRequest(String value);
}
