/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;


/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.SupervisorSettings}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SupervisorSettingsValidator {
	boolean validate();

	boolean validateExecutablePath(String value);
	boolean validateDeployed(boolean value);
	boolean validateSourcePath(String value);
	boolean validateCommands(String value);
	boolean validateSettings(String value);
}
