/**
 *
 * $Id$
 */
package eu.kalafatic.evolution.model.orchestration.validation;

import eu.kalafatic.evolution.model.orchestration.TestStatus;

/**
 * A sample validator interface for {@link eu.kalafatic.evolution.model.orchestration.Test}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateType(String value);
	boolean validatePath(String value);
	boolean validateStatus(TestStatus value);
	boolean validateSelected(boolean value);
}
