/**
 */
package eu.kalafatic.evolution.model.orchestration.provider;

import eu.kalafatic.evolution.model.orchestration.util.OrchestrationAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class OrchestrationItemProviderAdapterFactory extends OrchestrationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OrchestrationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Task} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TaskItemProvider taskItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Task}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTaskAdapter() {
		if (taskItemProvider == null) {
			taskItemProvider = new TaskItemProvider(this);
		}

		return taskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Agent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AgentItemProvider agentItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Agent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAgentAdapter() {
		if (agentItemProvider == null) {
			agentItemProvider = new AgentItemProvider(this);
		}

		return agentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Orchestrator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrchestratorItemProvider orchestratorItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Orchestrator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrchestratorAdapter() {
		if (orchestratorItemProvider == null) {
			orchestratorItemProvider = new OrchestratorItemProvider(this);
		}

		return orchestratorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Git} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GitItemProvider gitItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Git}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGitAdapter() {
		if (gitItemProvider == null) {
			gitItemProvider = new GitItemProvider(this);
		}

		return gitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Maven} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MavenItemProvider mavenItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Maven}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMavenAdapter() {
		if (mavenItemProvider == null) {
			mavenItemProvider = new MavenItemProvider(this);
		}

		return mavenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.LLM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LLMItemProvider llmItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.LLM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLLMAdapter() {
		if (llmItemProvider == null) {
			llmItemProvider = new LLMItemProvider(this);
		}

		return llmItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Compiler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompilerItemProvider compilerItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Compiler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompilerAdapter() {
		if (compilerItemProvider == null) {
			compilerItemProvider = new CompilerItemProvider(this);
		}

		return compilerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Command} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CommandItemProvider commandItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Command}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCommandAdapter() {
		if (commandItemProvider == null) {
			commandItemProvider = new CommandItemProvider(this);
		}

		return commandItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Ollama} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OllamaItemProvider ollamaItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Ollama}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOllamaAdapter() {
		if (ollamaItemProvider == null) {
			ollamaItemProvider = new OllamaItemProvider(this);
		}

		return ollamaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.AiChat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AiChatItemProvider aiChatItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.AiChat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAiChatAdapter() {
		if (aiChatItemProvider == null) {
			aiChatItemProvider = new AiChatItemProvider(this);
		}

		return aiChatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.NeuronAI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NeuronAIItemProvider neuronAIItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.NeuronAI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNeuronAIAdapter() {
		if (neuronAIItemProvider == null) {
			neuronAIItemProvider = new NeuronAIItemProvider(this);
		}

		return neuronAIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.EvoProject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvoProjectItemProvider evoProjectItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.EvoProject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvoProjectAdapter() {
		if (evoProjectItemProvider == null) {
			evoProjectItemProvider = new EvoProjectItemProvider(this);
		}

		return evoProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.AccessRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessRuleItemProvider accessRuleItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.AccessRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessRuleAdapter() {
		if (accessRuleItemProvider == null) {
			accessRuleItemProvider = new AccessRuleItemProvider(this);
		}

		return accessRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.NetworkRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NetworkRuleItemProvider networkRuleItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.NetworkRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNetworkRuleAdapter() {
		if (networkRuleItemProvider == null) {
			networkRuleItemProvider = new NetworkRuleItemProvider(this);
		}

		return networkRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.MemoryRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MemoryRuleItemProvider memoryRuleItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.MemoryRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMemoryRuleAdapter() {
		if (memoryRuleItemProvider == null) {
			memoryRuleItemProvider = new MemoryRuleItemProvider(this);
		}

		return memoryRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.SecretRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecretRuleItemProvider secretRuleItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.SecretRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecretRuleAdapter() {
		if (secretRuleItemProvider == null) {
			secretRuleItemProvider = new SecretRuleItemProvider(this);
		}

		return secretRuleItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.SelfDevSession} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelfDevSessionItemProvider selfDevSessionItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.SelfDevSession}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelfDevSessionAdapter() {
		if (selfDevSessionItemProvider == null) {
			selfDevSessionItemProvider = new SelfDevSessionItemProvider(this);
		}

		return selfDevSessionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Database} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatabaseItemProvider databaseItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Database}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatabaseAdapter() {
		if (databaseItemProvider == null) {
			databaseItemProvider = new DatabaseItemProvider(this);
		}

		return databaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.FileConfig} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileConfigItemProvider fileConfigItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.FileConfig}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileConfigAdapter() {
		if (fileConfigItemProvider == null) {
			fileConfigItemProvider = new FileConfigItemProvider(this);
		}

		return fileConfigItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Iteration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IterationItemProvider iterationItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Iteration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIterationAdapter() {
		if (iterationItemProvider == null) {
			iterationItemProvider = new IterationItemProvider(this);
		}

		return iterationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.Eclipse} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EclipseItemProvider eclipseItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.Eclipse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEclipseAdapter() {
		if (eclipseItemProvider == null) {
			eclipseItemProvider = new EclipseItemProvider(this);
		}

		return eclipseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eu.kalafatic.evolution.model.orchestration.EvaluationResult} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvaluationResultItemProvider evaluationResultItemProvider;

	/**
	 * This creates an adapter for a {@link eu.kalafatic.evolution.model.orchestration.EvaluationResult}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvaluationResultAdapter() {
		if (evaluationResultItemProvider == null) {
			evaluationResultItemProvider = new EvaluationResultItemProvider(this);
		}

		return evaluationResultItemProvider;
	}

	@Override
	public void dispose() {
		if (taskItemProvider != null) taskItemProvider.dispose();
		if (agentItemProvider != null) agentItemProvider.dispose();
		if (orchestratorItemProvider != null) orchestratorItemProvider.dispose();
		if (gitItemProvider != null) gitItemProvider.dispose();
		if (mavenItemProvider != null) mavenItemProvider.dispose();
		if (llmItemProvider != null) llmItemProvider.dispose();
		if (compilerItemProvider != null) compilerItemProvider.dispose();
		if (commandItemProvider != null) commandItemProvider.dispose();
		if (ollamaItemProvider != null) ollamaItemProvider.dispose();
		if (aiChatItemProvider != null) aiChatItemProvider.dispose();
		if (neuronAIItemProvider != null) neuronAIItemProvider.dispose();
		if (evoProjectItemProvider != null) evoProjectItemProvider.dispose();
		if (accessRuleItemProvider != null) accessRuleItemProvider.dispose();
		if (networkRuleItemProvider != null) networkRuleItemProvider.dispose();
		if (memoryRuleItemProvider != null) memoryRuleItemProvider.dispose();
		if (secretRuleItemProvider != null) secretRuleItemProvider.dispose();
		if (selfDevSessionItemProvider != null) selfDevSessionItemProvider.dispose();
		if (iterationItemProvider != null) iterationItemProvider.dispose();
		if (evaluationResultItemProvider != null) evaluationResultItemProvider.dispose();
	}

}
