source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               splash.bmp,\
               plugin_customization.ini,\
               chat.html,\
               workflow/,\
               js/,\
               css/,\
               lib/json-20140107.jar,\
               .
jars.extra.classpath = lib/json-20140107.jar
